language: 'node_js'

node_js: '14'

git:
  depth: 3

branches:
  only:
    - main

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
